### ISSUE TITLE
Refactor plan

### ISSUE THREAD

**Issue by callumrollo** [OceanGlidersCommunity/glidertest#44]
### A proposal for refactor

The main script `glidertest/tools.py` is becoming quite bloated. I propose refactoring into a few scripts for usability and maintainability. One suggestion:

- `glidertools/tools.py` the core functions like `test_temporal_drift` and `test_up_down_bias`
- `glidertools/plots.py` all plotting functionality, including cartopy maps
- glidertools/utilities.py` non-glider specific functions that an end user is unlikely to call directly like `sunrise_sunset` and `grid2d`

I am open to other suggestions!

The functions in plots would wrap the functions in tools so that e.g.

```python
def plot_updown_bais(ds):
    ds_bias = glidertools.tools.updown_bias(ds)
    ... <plotting stuff>
```

So a user can call `glidertools.tools.updown_bias(ds)` or `glidertools.plots.plot_updown_bias(ds)` depending on if they want plots or not.

In general, we should aim to use standard scientific python structure  (xarray datasets, pandas dataframes etc.) with standard variable names to pass data between functions rather than passing lists/arrays of temperature, salinity, pressure etc.

@MOchiara @eleanorfrajka 

Refactor checklist:

- [x] #102
- [ ] Consider an additional widgets module for functions the end user will not need to access
- [ ] Add themed blocks within each module for generic, CTD, bioptics, velocity for navigability
- [x] #94
- [x] #93
- [x] #99

**Comment by eleanorfrajka** [comment]
This sounds sensible to me, and will make things easier to parse going forward.  
From the w stuff then, `ramsey_binavg`, `calc_DEPTH_Z`, `calc_glider_w_from_depth`, `calc_seawater_w` -> tools.py, and
`plot_glider_track`, `plot_grid_spacing_histograms`, `plot_ts_histograms`, `plot_vertical_speeds_with_histograms`, `plot_combined_velocity_profiles` -> plots.py.

Can we also have some loose ordering of functions within each of tools.py or plots.py so it's easier to find things?  This can change, but maybe a section for generic, then specific to bioptics, then specific to CTD, then specific to W, etc.?  Won't change anything for the user.

Along the same lines, if tools.py gets even larger, is it possible/advisable to make another file called something like tools_widgets.py which can be imported within tools.py and not change the behaviour for the user?

For function naming, it would be useful to have some conventions.  My w functions are very wordy.   For instance, `calc_glider_w_from_depth` could be `calc_w_meas` (which adds the variable currently named `GLIDER_VERT_VELO_DZDT`, but called w_meas in papers).  Or `calc_seawater_w` could be `calc_w_sw` (to match the w_sw variable, which is called `VERT_CURR_MODEL`).  They'll be confusing anyway.. Oh, the convention I sort of adopted already was pre-pending `calc_*` when it adds a calculated variable to the xarray dataset.   

Several functions calculate absolute salinity and conservative temperature.  Perhaps this should be optionally calculated once as a `calc_teos10` or something.  Though if it's optional, functions which currently require `PSAL` in order to calculate `SA` would need extra checks for whether `SA` exists already.

I don't really know why we pass some `ax` as an optional argument in the plotting, but this could be the default across the board?   

Is there any value in adding a small comment after the docstrings with the authors?  In theory, we could figure this out from commits, but in practice, I wouldn't know how.  Might be useful if/when there are more contributors (but also might get out of date, and probably is supposed to be irrelevant)

**Comment by callumrollo** [comment]
Refactor checklist:

- [ ] split the content of `tools` up into modules `tools`, `plots` and `utilities`
- [ ] Consider an additional `widgets` module for functions the end user will not need to access
- [ ] Add themed blocks within each module for generic, CTD, bioptics, velocity for navigability
- [ ] Add a utility function like `_necessary_variables_check` which calculates derived variables like `SA` when needed and adds them to the dataset
- [ ] Add original function author and references to paper in docstrings

**Comment by callumrollo** [comment]
As to why we pass `ax` as an optional argument, this is for if the user has e.g. an existing multi-axes/multi-plot figure and they want to add a `glidertest` plot to one of those axes. It doesn't really make sense for the multiaxes figures like `plot_ts_histograms` which make multiple axes.

**Comment by MOchiara** [comment]
Do we have any idea of how we want to standardise the names of the functions? Do we have any references, actual convections or opinions?

**Comment by eleanorfrajka** [comment]
> As to why we pass `ax` as an optional argument, this is for if the user has e.g. an existing multi-axes/multi-plot figure and they want to add a `glidertest` plot to one of those axes. It doesn't really make sense for the multiaxes functions like `plot_ts_histograms` which make a plot with multiple axes.

Ok!  It also doesn't look as nice when running it in `demo.ipynb` and the function outputs are dumped to the screen.  Possibly it means things like plot_ts_histograms should be broken into 1-d and 2-d histogram plotting functions, which are then called by a plot_ts_histograms plot...

**Comment by MOchiara** [comment]
At the moment we have those names
*  _necessary_variables_check()
*  _calc_teos10_variables()
* compute_grid2d()
* compute_updown_bias()
* plot_updown_bias()
* compute_cline()
* plot_basic_vars()
* process_optics_assess()
* compute_sunset_sunrise()
* compute_daynight_avg()
* plot_daynight_avg()
* plot_quench_assess()
* check_temporal_drift()
* check_monotony()
* plot_profIncrease()
* plot_glider_track()
* plot_grid_spacing()
* plot_ts()
* calc_DEPTH_Z()
* calc_w_meas()
* calc_w_sw()
* plot_vertical_speeds_with_histograms()
* compute_ramsey_binavg()
* plot_combined_velocity_profiles()

**Comment by MOchiara** [comment]
I like the `quant_` so if we want to we can change:
* compute_updown_bias()
* compute_ramsey_binavg()
 I think the other `compute_` are better with `compute_`  than `quant_` 

`compute_ramsey_binavg()` can be changed to `compute_binavg()` (or `quant_)`

For `grid2d` I think your suggestion to `construct_2dgrid` is very good

Opinions?

**Comment by callumrollo** [comment]
sounds good to me! Go ahead and rename

**Comment by eleanorfrajka** [comment]
So, apparently a "quant" is a person who does financial trading.
